### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by maaa101** [SpriteOvO/AirPodsDesktop#45] opened 2022-10-02 15:48 UTC
A Linux release would be pretty nice, i don't think it would take a lot of effort to get it running on Linux

**Comment by SpriteOvO** [comment] 2022-10-02 16:13
Duplicate of #28 (see https://github.com/SpriteOvO/AirPodsDesktop/issues/28#issuecomment-1217885292 and https://github.com/SpriteOvO/AirPodsDesktop/issues/43#issuecomment-1221307801)

The main challenge in porting to Linux is Bluetooth related code, which is currently platform specific. On Windows it is implemented by using `winrt`.

I've been working on several other projects recently, and I'll be back to maintain this AirPodsDekstop project when they reach some targets. Sorry for the temporary lack of maintenance in this repository.

**Closed** 2022-10-02 16:13 UTC
Labels: :link: duplicate
