### ISSUE TITLE
i have my airpods connected but it says no paired device found [Bug Report] 

### ISSUE THREAD

**Issue by w3qxx** [SpriteOvO/AirPodsDesktop#65] opened 2023-04-30 13:05 UTC
![изображение_2023-04-30_160412383](https://user-images.githubusercontent.com/132206816/235354397-b661c2c8-42f3-4559-bc18-a28278289cf9.png)

## :gear: **Environments:** 
 - OS: [e.g. Windows 10 20H2]
 - Version: [e.g. 0.1.0]

## :star2: **Additional context**

<details><summary><b>AirPodsDesktop.log</b></summary>

```
Launch AirPodsDesktop with "--trace" parameter.
Then after the bug occurred, insert the contents of "AirPodsDesktop.log" here.
```
</details>

<details><summary><b>StackTrace.log</b></summary>

```
Insert the contents of "StackTrace.log" here, if any.
```
</details>

**Comment by SpriteOvO** [comment] 2023-07-27 21:17
If your device is AirPods Pro 2, this issue is a duplicate of #46. Will be release in a few hours.

If not, please reopen this issue.

**Closed by SpriteOvO** 2023-07-27 21:17 UTC
