### ISSUE TITLE
[Bug Report]  Airpods Max not detected

### ISSUE THREAD

**Issue by NextdoorPsycho** [SpriteOvO/AirPodsDesktop#69] opened 2023-06-29 05:40 UTC
## :bug: **Describe the bug**
Airpods max arent connecting

https://github.com/SpriteOvO/AirPodsDesktop/issues/26
This is a duplicate of this, in that it has not been resolved and im checking on the status of this repo in hopes to get it updated

**Comment by SpriteOvO** [comment] 2023-07-27 21:36
Duplicate of #26.

Initial support for AirPods Max will be included in the upcoming v0.4.0 (proper device detection), but since it works with a different logic than the other AirPods (AirPods Max is all-in-one), it may not display the information correctly, and I'll try to fix it later.

**Closed by SpriteOvO** 2023-07-27 21:36 UTC
