### ISSUE TITLE
i have my airpods connected but wont show in app

### ISSUE THREAD

**Issue by DaZoZElMoz** [SpriteOvO/AirPodsDesktop#60] opened 2023-02-17 21:07 UTC
## :bug: **Describe the bug**
i hvae my airpods connected but i have nothing in the app it says disconnected

## :scroll: **To Reproduce**
1. Go to hidden icons
2. Click on .'the app logo
4. See error disconnected

## :rocket: **Expected behavior**
taht  it should show battery life

## :framed_picture: **Screenshots**
![image](https://user-images.githubusercontent.com/124311096/219793142-dc20a02b-34ef-41ad-9cd0-3ce34389d278.png)

## :gear: **Environments:** 
 - OS: [e.g. Windows 11 20H2]
 - Version: [e.g. 0.1.0]
 - 
![image](https://user-images.githubusercontent.com/124311096/219793069-3a458170-152b-44ab-a336-9a082842bb09.png)

## :star2: **Additional context**

[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/10771718/AirPodsDesktop.log)

<details><summary><b>AirPodsDesktop.log</b></summary>

```
Launch AirPodsDesktop with "--trace" parameter.
Then after the bug occurred, insert the contents of "AirPodsDesktop.log" here.
```
</details>

<details><summary><b>StackTrace.log</b></summary>

```
Insert the contents of "StackTrace.log" here, if any.
```
</details>

**Comment by NotNexuss** [comment] 2023-03-14 11:35
I have the same issue here

**Comment by SpriteOvO** [comment] 2023-07-27 21:16
If your device is AirPods Pro 2, this issue is a duplicate of #46. Will be release in a few hours.

If not, please reopen this issue.

**Closed by SpriteOvO** 2023-07-27 21:16 UTC
