### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Agame7k** [SpriteOvO/AirPodsDesktop#62] opened 2023-03-18 22:05 UTC
## :bug: **Describe the bug**
Airpods pro 2 being reconized

## :rocket: **Expected behavior**
I am using the build for the airpods pro 2 branch and it does not get reconized 

## :framed_picture: **Screenshots**
![image](https://user-images.githubusercontent.com/119633821/226142523-28e86e42-762d-4002-9b24-3ceef4baf07f.png)
![image](https://user-images.githubusercontent.com/119633821/226142682-b6357b44-69a6-46ec-954c-21a54c14dddc.png)

## :gear: **Environments:** 
 - OS: Windows 11 22H2
 - Version: 22624.1465

## :star2: **Additional context**

```
Launch AirPodsDesktop with "--trace" parameter.
Then after the bug occurred, insert the contents of "AirPodsDesktop.log" here.
```
</details>
 
[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/11009707/AirPodsDesktop.log)

<details><summary><b>StackTrace.log</b></summary>

```
Insert the contents of "StackTrace.log" here, if any.
```
</details>

**Comment by SpriteOvO** [comment] 2023-07-27 21:09
Duplicate of #46

**Closed by SpriteOvO** 2023-07-27 21:09 UTC
