### ISSUE TITLE
The main branch still doesn't support AirPods Pro 2

### ISSUE THREAD

**Issue by Desynci** [SpriteOvO/AirPodsDesktop#59] opened 2023-02-10 10:43 UTC
Hi there, how about merging the _airpods-pro-2_ and the _main_ branches? As I noticed, there's still no support for the Pro 2 model in main, cause of missing it's _ModelId_ in the _AirPods::getModel_ function.

So, fixed one: https://github.com/SpriteOvO/AirPodsDesktop/blob/faad5457ed4cb27fa569ff1e28a7ab74b942b753/Source/Core/AppleCP.cpp#L54
Doesn't fixed (open and look below): https://github.com/SpriteOvO/AirPodsDesktop/blob/175f7df9a40fe205533dc1e50c5397949934d88f/Source/Core/AppleCP.cpp#L42

Greetings.

**Comment by SpriteOvO** [comment] 2023-02-10 10:59
I will run the CI on that branch so that you can get the installer artifact after it finished compilation.

The reason I still don't want to merge these branches is that the animations are still not ready, and they need to be extracted from unpacked iOS. I kinda forgot how to do it.

I'm still busy with other things, my work, my studies. I apologize for the inconveniences.

**Comment by SpriteOvO** [comment] 2023-02-10 11:00
https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/4143238645

**Comment by Desynci** [comment] 2023-02-10 12:28
> https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/4143238645

It works, thank you. But there is a small problem with the display of the case charge:
![2023-02-10_191248](https://user-images.githubusercontent.com/66823992/218089728-746e096d-fa4f-43e4-abad-cd93cf556e6d.png)

Also, if it's not too much trouble, could you explain how the smaller input latency works? I tried to enable this option, but seems that there's no major sound's latency decrease.

Or maybe there's another way to reduce it if you know?

**Comment by SpriteOvO** [comment] 2023-07-27 21:15
Duplicate of #46. Will be release in a few hours.

**Closed by SpriteOvO** 2023-07-27 21:15 UTC

**Comment by SpriteOvO** [comment] 2023-07-27 22:33
> Also, if it's not too much trouble, could you explain how the smaller input latency works? I tried to enable this option, but seems that there's no major sound's latency decrease.
> 
> Or maybe there's another way to reduce it if you know?

@Desynci Normally, if there is no sound output from your system for a period of time, AirPods will go into an inactive mute mode. Then when your system makes sound, it takes a short time (about 1 second or so) between switching from inactive to active mode. This results in the possibility that AirPods may not produce any sound if your system plays a sound shorter than 1 second, or you may only hear the incomplete second half of the sound. `low audio latency` solves this problem by looping a silent MP3 to keep AirPods active.
