### ISSUE TITLE
[Feature Request] airpods pro gen 2 support pretty please????

### ISSUE THREAD

**Issue by noxxspire** [SpriteOvO/AirPodsDesktop#70] opened 2023-07-14 04:26 UTC
## :cloud_with_rain: **Is your feature request related to a problem? Please describe.**
my airpods pro gen 2 never connects to airpodsdesktop even if i put it in pairing mode

## :partly_sunny: **Describe the solution you'd like**
the airpods pro would connect automatically to the app, with battery percentages and with all settings available to change (like transparency, spatial audio and ANC)

## :cloud: **Describe alternatives you've considered**
at least only show the battery

## :star2: **Additional context**
![image_2023-07-14_095519226](https://github.com/SpriteOvO/AirPodsDesktop/assets/128416885/7677434e-5da2-4fbd-9a2b-94dec9282e44)

![opera_3rs4DFCPJB](https://github.com/SpriteOvO/AirPodsDesktop/assets/128416885/83b65bb7-58c8-4e36-8893-2340d003e968)
![image_2023-07-14_104109327](https://github.com/SpriteOvO/AirPodsDesktop/assets/128416885/5b5ac767-45a5-48d1-8fdd-23aac27d7ca0)

**Comment by noxxspire** [comment] 2023-07-14 05:05
here is the log of me trying to connect to the app
[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/12046368/AirPodsDesktop.log)

**Comment by noxxspire** [comment] 2023-07-14 05:06
sorry i accidentally closed it

**Comment by arbaran** [comment] 2023-07-26 16:22
I was unable to do this either; are we sure this is a missing feature? Does it depend on what the AirPods are named, because I named mine something without "AirPods" in it at first but then added back "(AirPods Pro)" into it

**Comment by SpriteOvO** [comment] 2023-07-27 21:10
Duplicate of #46. Will be release in a few hours.

**Closed by SpriteOvO** 2023-07-27 21:10 UTC
