### ISSUE TITLE
[Bug Report] High CPU usage

### ISSUE THREAD

**Issue by AnnAngela** [SpriteOvO/AirPodsDesktop#20] opened 2021-12-21 00:59 UTC
## :bug: **Describe the bug**
The program continuously takes up a lot of CPU usage, even when the Air pods are not connected.

## :scroll: **Screenshot**
![T_XBML)@KU2IT`42J}XF3O3](https://user-images.githubusercontent.com/9762652/146852605-fee66983-15c0-4330-bbd4-b5cb5a38a11d.png)

## :gear: **Environments:** 
 - OS: Windows 10 Pro Version 21H1 19043.1266
 - Version: v0.3.1
 - CPU: Intel Core i7-7700

<details><summary><b>AirPodsDesktop.log</b></summary>

All the logs contain same line:
```
[2021-12-21 08:53:50.558] [Main] [warning] [LowAudioLatency.cpp:53] LowAudioLatency::Controller error: 1
```
</details>

<details><summary><b>StackTrace.log</b></summary>

```
Not Found.
```
</details>

**Comment by SpriteOvO** [comment] 2021-12-21 08:42
![1](https://user-images.githubusercontent.com/33660554/146897409-0796d74b-dacd-4dc0-9beb-7d5fdbc3e104.png)

I can't reproduce this problem.

Could you describe the situation in more details? Does the high CPU usage occur at launch or after a while? What features do you have enabled? Did that warning log only appear once or keep repeating?

**Comment by SpriteOvO** [comment] 2021-12-25 05:04
@AnnAngela If you disable `low audio latency` will the high CPU usage stop? If so, what's causing it looks like `QMediaPlayer` isn't playing MP3 correctly. This may be a rare issue and I'll look into it.

**Comment by AnnAngela** [comment] 2021-12-27 01:18
@SpriteOvO  Yes, with `low audio latency` disabled, the cpu usage dropped down to nearly zero
![image](https://user-images.githubusercontent.com/9762652/147425047-42f69ca7-f16c-402f-8a5f-25c4d79e9ce8.png)

**Comment by SpriteOvO** [comment] 2021-12-28 06:27
I tried [this SO answer](https://stackoverflow.com/a/22621094), regenerated the `Silence.mp3` with ID3 v2.3, could you try [the artifact](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/1629480804) of commit ddf601f13d81da2088a7604d238e2a8aed40eddd to check if it fixed the bug?

**Comment by AnnAngela** [comment] 2021-12-29 02:08
I'm sorry I'm on vacation now, I will test it after January 3rd.

**Comment by AnnAngela** [comment] 2022-01-01 02:27
@SpriteOvO I tried the artifact you linked and here's the result:
![image](https://user-images.githubusercontent.com/9762652/147842779-a23941a3-ba15-4583-add2-eca6a7d8ad74.png)
It's still a bit higher but way more acceptable.

**Comment by SpriteOvO** [comment] 2022-01-01 05:19
@AnnAngela No more repeat warnings in the log?

`low audio latency` works by looping a silent MP3 to keep the AirPods active. I'm not sure if the 2.59 (percentage?) for playing MP3 is normal, although mine is around 0.1 (i9-10900KF).

**Comment by AnnAngela** [comment] 2022-01-03 01:08
> @AnnAngela No more repeat warnings in the log?
> 
> `low audio latency` works by looping a silent MP3 to keep the AirPods active. I'm not sure if the 2.59 (percentage?) for playing MP3 is normal, although mine is around 0.1 (i9-10900KF).

Hmmmm, after a reboot, the warning message reappeared again.
```
[2022-01-03 09:01:29.838] [Main] [warning] [LowAudioLatency.cpp:53] LowAudioLatency::Controller error: 1
```
IDK why =。=

**Comment by SpriteOvO** [comment] 2022-01-03 10:52
@AnnAngela `AirPodsDesktop` will log the git hash when it starts, or you can check the git hash in Settings About, can you confirm it is ddf601f13d81da2088a7604d238e2a8aed40eddd commit?

**Comment by AnnAngela** [comment] 2022-01-04 01:40
@SpriteOvO Affirmative.
![image](https://user-images.githubusercontent.com/9762652/147998486-bc52ef8d-c565-4921-81bb-a2f369bc8532.png)

**Comment by SpriteOvO** [comment] 2022-01-04 03:39
I can't reproduce this error on my PC and I searched as much as I could, but didn't find any more useful information. Could you try this commit (d4b4ce998433b7115995679daeb9e71c54ea764d) [artifact](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/1652019879)? It will always open a console and if there are any Qt internal errors written to `stdout` / `stderr`, you will see them. Thanks!

**Comment by AnnAngela** [comment] 2022-01-04 07:21
@SpriteOvO It keeps showing:
```
DirectShowPlayerService::doRender: Unknown error 0x8004022a.
```
![image](https://user-images.githubusercontent.com/9762652/148023141-e8ee5a30-4f42-4429-abde-1f1a7e859ed9.png)

**Comment by AnnAngela** [comment] 2022-01-04 07:27
Sometimes, when I ran the program after airpods pro connected, the problems gone and no error reported.

But when I ran the program firstly and connected airpods pro after, the problems came out.

**Comment by SpriteOvO** [comment] 2022-01-04 13:20
@AnnAngela Thanks for the info, I have reproduced it on my PC. Try this commit (fca503c6ea719cc062325a7ef8f6f8b59ed91b4d) [artifact](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/1653782112), it works for me.

**Comment by AnnAngela** [comment] 2022-01-05 02:05
@SpriteOvO This commit artifact works just fine, LGTM!

**Comment by SpriteOvO** [comment] 2022-01-05 02:08
@AnnAngela Thank you very much too! Without you this bug could not be fixed.

**Comment by AnnAngela** [comment] 2022-01-05 02:11
[This comment](https://github.com/SpriteOvO/AirPodsDesktop/blob/fca503c6ea719cc062325a7ef8f6f8b59ed91b4d/Source/Core/LowAudioLatency.cpp#L51) is right, my workspace pc has no other audio output except the airpods, and I think that is the problem.

**Comment by AnnAngela** [comment] 2022-01-05 06:46
@SpriteOvO There is another problem, when I came back to my pc in the afternoon , the program started using high CPU usage again. The log is similar:
```
[2022-01-05 14:37:31.880] [Main] [warning] [LowAudioLatency.cpp:98] LowAudioLatency::Controller error: 1
```
Maybe the program should detect if there is another audio output device or not when the airpods disconnecting, and if not the `QMediaPlayer` should be stop.

**Comment by SpriteOvO** [comment] 2022-01-05 07:01
@AnnAngela A little strange, I can't reproduce it. For me, it just needs to have at least one available audio output device at the time of initialization, so that warning will no longer appear, even if no device is available again afterwards.

**Comment by SpriteOvO** [comment] 2022-01-05 07:40
Stop and reinitialize `QMediaPlayer` later if an error occurs, it should fix the bug. BTW, Qt always has some glitches that challenge its users, I'm used to it, lol.

**Comment by SpriteOvO** [comment] 2022-01-13 13:44
Close as this bug should be fixed in 73493fbb4d60c138eb567ff3d1bdd20593955a47 commit. If there are still problems, feel free to reopen it.

**Closed** 2022-01-13 13:44 UTC
Labels: :bug: bug

**Comment by AnnAngela** [comment] 2022-01-14 06:53
I tried the latest artifate and it looks good to me. Even after a long time without any audio output device, the program didn't throw any error at all.

**Comment by widget-** [comment] 2023-01-07 01:57
> `low audio latency` works by looping a silent MP3 to keep the AirPods active. I'm not sure if the 2.59 (percentage?) for playing MP3 is normal, although mine is around 0.1 (i9-10900KF).

@SpriteOvO  Any chance you could add this to the readme (or just mention it's for resuming audio playback faster)? My first impression was that this somehow added codec support for something like AptX Low Latency but then I realized that's probably not what it was doing.
