### ISSUE TITLE
i cant bind my airpods

### ISSUE THREAD

**Issue by zMuh** [SpriteOvO/AirPodsDesktop#57] opened 2023-01-01 07:22 UTC
when i try to open the program it dosent detect my air pods i tried to unpair it and i still have the same problem 

i have air pods pro gen 2

![image](https://user-images.githubusercontent.com/85467517/210163665-5fe684f4-61ac-473c-a4b1-adf817a5ec1b.png)

[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/10328464/AirPodsDesktop.log)

**Comment by mikhailfluffy** [comment] 2023-01-03 05:41
I think It's not supported. Last update was 4 Feb 2022

**Comment by miguelreb** [comment] 2023-02-03 12:08
Same problem here.

**Comment by dener120** [comment] 2023-02-05 13:32
Similar problem

**Comment by CaptainMudkip1** [comment] 2023-02-09 19:28
Same problem.

**Comment by Jadtrugaming** [comment] 2023-02-11 02:02
@SpriteOvO When do you think this will be fixed?

**Comment by jbird2409** [comment] 2023-03-12 22:30
i have orginal airpods gen 2 and same here

**Comment by DanielOberlechner** [comment] 2023-03-26 14:09
I've got this issue with my Apple Airpods Max and I don't know how to fix it ...
If anyone has an idea just hit me up please :)

**Comment by shinjaxu** [comment] 2023-06-09 12:05
Same problem

**Comment by SpriteOvO** [comment] 2023-07-27 21:14
Duplicate of #46. Will be release in a few hours.

**Closed by SpriteOvO** 2023-07-27 21:14 UTC
